name = "bhaskar"
license = "MIT"
licenselink = "https://github.com/spf13/hyde/blob/master/LICENSE.md"
description = "An DevSceOps and Trader"
tags = ["blog", "company"]
features = ["blog", "themes", "disqus"]
min_version = 0.53

[author]
    name = "bhaskar"
    homepage = "http://bhaskarvilles.dev"

theme = "hyde"

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/bhaskarvilles/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/bhaskarvilles/"}
  ]
  
theme = "hyde"

[params]
  description = "Hacker, Developer, DevSecOps and Trader"

theme = "hyde"

[params]
  themeColor = "theme-base-08"

theme = "hyde"

[params]
  layoutReverse = true
